Q1. Create the first numpy array of 1-D with values (1,2,3,0).
 Create a second numpy array of 1-D with values (4,1,0,
 6). Perform following simple arithme�c opera�ons on
 these two numpy arrays:
 • Addi�on
 • Subtrac�on
 • Mul�plica�on
 • Division

In [5]:
import numpy as np
a = np.array([1,2,3,0])
b = np.array([4,1,0,6])
print(a)
print(b)

[1 2 3 0]
[4 1 0 6]


In [7]:
#Addition
a+b
print(a+b)

[5 3 3 6]


In [9]:
#Subtraction
a-b
print(a-b)

[-3  1  3 -6]


In [11]:
#multiplication
a*b
print(a*b)

[4 2 0 0]


In [13]:
#Division
result = a/b
print(result)

[0.25 2.    inf 0.  ]


C:\Users\under\AppData\Local\Temp\ipykernel_10708\55919365.py:2: RuntimeWarning: divide by zero encountered in divide
  result = a/b


Q2. Create the first numpy array of random integers
 between 1-100 of 5 elements in 1-D. Create second
 numpy array of 2-D for the same range of integers of
 shape 4*5. Now perform following simple arithme�c
 opera�ons on these two numpy arrays:
 • Addi�on
 • Subtrac�on

In [16]:
a1=np.random.randint(1,100,5)
a2= np.random.randint(1,100,(4,5))
print(a1)
print(a2)
#addition
print("Addition:",(a1+a2)) #broadcasting, here a1 is 1D,(5) and a2 is 2D with dimensions (4,5). a1 is converted to 2D, (1,5) and streched to (4,5)
#subtraction
print("Subtraction:",(a1-a2))

[43 94 33 53 82]
[[46  4 33 95 45]
 [54 86 51 86 71]
 [ 7 38 88 10 35]
 [62 98 95 61 13]]
Addition: [[ 89  98  66 148 127]
 [ 97 180  84 139 153]
 [ 50 132 121  63 117]
 [105 192 128 114  95]]
Subtraction: [[ -3  90   0 -42  37]
 [-11   8 -18 -33  11]
 [ 36  56 -55  43  47]
 [-19  -4 -62  -8  69]]


Q3. Create a 3-D array of 27 random elements using random
 func�on of shape 3*3*3. Now pull the following
 elements using indexing/slicing
 •Third column of second 2-D array
 • First and third row of first 2-D array
 • Intersec�on of first row and third column in
 third 2-D aray

In [19]:
b1 = np.random.randint(1,100,27).reshape(3,3,3)
b1


array([[[68, 38, 61],
        [47, 24, 46],
        [53, 61,  1]],

       [[25,  9, 40],
        [15, 17, 79],
        [73, 88, 81]],

       [[ 6, 61, 45],
        [ 2, 69, 95],
        [29, 69, 98]]])

In [21]:
#Third column of second 2-D array
b1[1,:,2]

array([40, 79, 81])

In [23]:
#First and third row of first 2-D array
b1[0,0:3:2,:]

array([[68, 38, 61],
       [53, 61,  1]])

In [25]:
#Intersec�on of first row and third column in third 2-D aray
b1[2,0,2]

45

Q4. Create a 2-D numpy array of random integers between
 1 to 100 with shape 5*4. Now perform following
 opera�ons: 
 • Print only the even numbers from this array
 • Print only the odd numbers from this array
 • Print row wise sum of all elements
 • Print column wise sum of all elements
 • Convert this 2-D array into 3-D array of shape
 2*2*5 

In [28]:
c1=np.random.randint(1,100,(5,4))
c1

array([[75, 96, 74, 31],
       [90, 20, 27, 11],
       [74, 42, 21, 31],
       [26, 89,  6, 75],
       [72, 19, 73, 19]])

In [30]:
#Print only the even numbers from this array
c1[c1%2==0]

array([96, 74, 90, 20, 74, 42, 26,  6, 72])

In [32]:
#Print only the odd numbers from this array
c1[~c1%2==0]

array([75, 31, 27, 11, 21, 31, 89, 75, 19, 73, 19])

In [34]:
#Print column wise sum of all elements
np.sum(c1,axis=0)

array([337, 266, 201, 167])

In [36]:
#Convert this 2-D array into 3-D array of shape 2*2*5 
c1_reshape = c1.reshape((2,2,5))
c1_reshape

array([[[75, 96, 74, 31, 90],
        [20, 27, 11, 74, 42]],

       [[21, 31, 26, 89,  6],
        [75, 72, 19, 73, 19]]])

Q5. Create a 2-D numpy array of random integers between
 1 to 100 with shape 5*4. Now perform following
 opera�ons:
 • Swap first row with third row
 • Swap second column with fourth column.
 • Replace the values less than 50 with zero.
 • Convert this 2D array into 1-D array

In [39]:
d1= np.random.randint(1,100,(5,4))
d1

array([[39, 18, 82,  6],
       [98, 53, 69, 87],
       [95, 55, 27, 76],
       [61, 59, 17, 80],
       [52, 99, 88, 82]])

In [41]:
#Swap first row with third row
d2=np.array(d1)
d2[[0, 2]] = d2[[2, 0]]
d2

array([[95, 55, 27, 76],
       [98, 53, 69, 87],
       [39, 18, 82,  6],
       [61, 59, 17, 80],
       [52, 99, 88, 82]])

In [43]:
#Swap second column with fourth column.
d3=np.array(d1)
d3[:,[1,3]]=d3[:,[3,1]]
d3

array([[39,  6, 82, 18],
       [98, 87, 69, 53],
       [95, 76, 27, 55],
       [61, 80, 17, 59],
       [52, 82, 88, 99]])

In [45]:
# Replace the values less than 50 with zero.
np.where(d1<50,0,d1)

array([[ 0,  0, 82,  0],
       [98, 53, 69, 87],
       [95, 55,  0, 76],
       [61, 59,  0, 80],
       [52, 99, 88, 82]])

In [47]:
#Convert this 2D array into 1-D array
d4=d1.ravel()
d4

array([39, 18, 82,  6, 98, 53, 69, 87, 95, 55, 27, 76, 61, 59, 17, 80, 52,
       99, 88, 82])

Q6. Explain the concept of stacking in numpy with examples.
 How is it different from concatena�on. Give any 3
 differences between them

Stacking in NumPy refers to joining multiple arrays along a new axis. This results in an increase in the dimensionality of the arrays. Essentially, it "stacks" arrays along an axis that is added to the original arrays.
Types of Stacking:
Vertical Stacking (np.vstack()): Stack arrays vertically ie along rows. adds a dimension
Horizontal Stacking (np.hstack()): Stack arrays horizontally, ie along columns.

In [51]:
#example of verticle stacking & horizental stacking
a = np.array([1, 2])
b = np.array([5, 6])
verticle_stack = np.vstack((a, b))
horizental_stack = np.hstack((a, b))
print("VERTICLE STACKING:",verticle_stack)
print("HORIZENTAL STACKING:",horizental_stack)

VERTICLE STACKING: [[1 2]
 [5 6]]
HORIZENTAL STACKING: [1 2 5 6]


Concatenation in NumPy refers to the operation of joining two or more arrays along a specific axis. Unlike stacking, concatenation does not add any new axes to the arrays. Instead, it combines arrays along an existing axis, either row-wise (axis 0) or column-wise (axis 1)

In [55]:
#example
arr1 = np.array([1, 2])
arr2 = np.array([5, 6])

concatenated = np.concatenate((arr1, arr2)) 
print(concatenated)

[1 2 5 6]


Three difference between stacking and concatenate are:
1.New Axis vs. Existing Axis: Stacking adds a new axis to combine the arrays. The result will have one more dimension than the original arrays.
Whereas concatenation combines arrays along an existing axis without adding new dimensions.

2.Function Used: The np.stack() function is used to add a new axis for stacking arrays.
The np.concatenate() function is used to merge arrays along a specified axis.

3.Dimensionality: Stacking increases the number of dimensions by one.Concatenation Keeps the same number of dimensions as the arrays being combined.